### ISSUE TITLE
Getting error when doing cattkin make

### ISSUE THREAD

**Issue by aba01kz** [ross1573/scan_3d#1]
Hi, I am doing rplidar 3D mapping. when it is vertically located and scanning. So when I download your rep, and tried to catkin_make, it shows errors. I am using Rpi4 and ubuntu 20.04, ROS noetic. The error says: It requires C++ 14 and above. Could you help me?

**Comment by ross1573** [comment]
Sorry for the late response. It seems that requirement of some packages has been changed. Could you please try changing 'CMAKE_CXX_FLAGS' in 'CMakeLists.txt' from "-std=c++11" to "-std=c++14" or above?

**Comment by aba01kz** [comment]
Thank you it helped, But I met another problem with RPlidardata package. IN the CMakefile.txt, there is written add_executables (rplidardata src/node) but in the rplidarData package there is no src/node file. I tried to add src from rplidar_ros package, but id doesnt work.

**Comment by ross1573** [comment]
Glad it helped. And for your second problem, src/node.cpp is the file in rplidar_ros repo (unmodified).
rplidar_data folder should be same as rplidar_ros except for files in this repo (launch, cmake, packages).
You should duplicate rplidar_ros folder (in [repo](https://github.com/Slamtec/rplidar_ros.git)) with the name of rplidar_data and overwrite files in this repo.
This work must be done on hector_slam and rplidar_ros folders too.

I'm not sure why I haven't included those files in the repo, but I think it was kind of a licensing problem.
Sorry for the inconvenience anyway.

**Comment by aba01kz** [comment]
Thank you, I changed some lines there now working. One more question, how to save vertical lidar data like you did?

**Comment by ross1573** [comment]
That feature is part of view_3d [(pcl_view.cpp)](https://github.com/ross1573/scan_3d/blob/master/scan_3d/src/pcl_view.cpp)
As you can see in line 94, program will ask you to save current data in a specified location.
This will happen after ros end's, and file will not be saved when just pressing enter.
And when you pass such file location to view_3d as argument, the program will just display the file (and does not render current lidar data).

Since my implementation just dumps every points in every frame, program will became highly buggy after few mins.
So feel free to make your own implementation of visualizing the data.

**Comment by aba01kz** [comment]
Terribly sorry for annoying you over and over.
I am a second year student and doing the project with lidar and 3D mapping exactly like yours. I am beginner in Robotics. But only with vertical lidar and camera. You said that in pcl_view there is function to save 3D map. I am running only slam.launch (in terminal I run roslaunch slam.launch). What I should do to get 3D map? Thank you so much!

**Comment by ross1573** [comment]
First of all, this project is based on 2 rplidars. 
So if you wish to use anything instead, you probably should modify the source code (or rewrite bunch of it..)
I was able to capture 3d data by grabbing 2 rplidars as below.

Secondly, if you want to visualize your data, you should open up a new terminal and run view_3d.
slam.launch file does include launch files for two rplidars, hector_mapping and scan_3d but not view_3d.
This was due to performance issue which is mentioned above.
So view_3d must run on separate process.

Since I have deleted the project from my computer, I’m not sure which one is the right file.
But since, CMakeLists.txt contains view_3d as executable, there will be an executable named view_3d.
I’m terribly sorry that the answer might not help much, but I dont have enough time to replicate the project anymore..

![Uploading IMG_3073-cutout.png…]()

**Comment by aba01kz** [comment]
I am sorry again, I could not find view_3d in the repository here. Could you please send it to aba01kz@gmail.com or maybe add to the rep? It will be really helpful for me.

**Comment by ross1573** [comment]
Sorry to tell you that I have moved on to apple silicon mac which isn't supported by the ros neotic.
And since it's the only machine I have, there's no other way to build a solution at the moment.
I'm currently working on this issue, but it may take some time and cannot guarantee the result.
When I'm finished dealing with the build, I will update the repo and mail you.

**Comment by ross1573** [comment]
Updated repo with all source files included. 
Now you probably won't encounter any issues when using catkin_make. 
I'll update the README with the short guide in a week or so.

**Comment by aba01kz** [comment]
Thank you! I am doing same job getting 3D map with two rplidars. Tried to merge laserscans with ira_laser_tools. It worked. Now dealing with saving pointcloud and working with SLAM algorithms.

**Comment by ross1573** [comment]
Good for you!
Now I guess it time to close this issue.
If you have any new issues or questions, feel free to reopen this issue or just make another one.
